lga = {
    "1": "Akinyele",
    "2": "Iseyin",
    "3": "Oluyole",
    "4": "Ibadan North",
    "5": "Ibadan North East",
    "6": "Ibadan North West",
    "7": "Ibadan South East",
    "8": "Ibadan South West",
    "9": "Lagelu",
    "10": "Egbeda",
    "11": "Ona Ara",
    "12": "Iwajowa",
    "13": "Kajola",
    "14": "Atisbo",
    "15": "Itesiwaju",
    "16": "Saki East",
    "17": "Saki West",
    "18": "Ibarapa North",
    "19": "Ibarapa East",
    "20": "Ibarapa Central",
    "21": "Ido",
    "22": "Ori Ire",
    "23": "Oyo West",
    "24": "Oyo East",
    "25": "Afijio",
    "26": "Oluyole",
    "27": "Ogbomosho North",
    "28": "Ogbomosho South",
    "29": "Surulere",
    "30": "Ogo Oluwa",
    "31": "Irepo",
    "32": "Orelope",
    "33": "Olorunsogo"
}

town = {
    "1": "town 1",
    "2": "town 2",
    "3": "town 3",
    "4": "town 4",
    "5": "town 5",
    "6": "town 6",
    "7": "town 7",
    "8": "town 8",
    "9": "town 9",
    "10": "town 10",
    "11": "town 11",
    "12": "town 12",
    "13": "town 13",
    "14": "town 14",
    "15": "town 15",
    "16": "town 16",
    "17": "town 17",
    "18": "town 18",
    "19": "town 19",
    "20": "town 20",
}

hospitals = {
    "1": "hospital 1",
    "2": "hospital 2",
    "3": "hospital 3",
    "4": "hospital 4",
    "5": "hospital 5",
}

pharmacies = {
    "1": "pharmacy 1",
    "2": "pharmacy 2",
    "3": "pharmacy 3",
    "4": "pharmacy 4",
    "5": "pharmacy 5",
}

laboratories = {
    "1": "laboratory 1",
    "2": "laboratory 2",
    "3": "laboratory 3",
    "4": "laboratory 4",
    "5": "laboratory 5",
}

# s = string
# d = digit
response_text = {
    "0": "CON Welcome to Oyo State Tele-medicine Service",
    "0*1": "1. Register",
    "0*2": "2. Quit",
    "1": "CON Input Fullname",
    "1-details": "(Surname Firstname Lastname)",
    "1*s": "CON Select Gender",
    "1*s*1": "1. Male",
    "1*s*2": "2. Female",
    "1*s*d*s": "CON Input Date of Birth",
    "1*s*d*s-ddmmyy": "(DD-MM-YYYY)",
    "1*s*d*s*s": "CON Select Local Govt. Area",
    "1*s*d*s*s-lga*1": "1. {}".format(lga['1']),
    "1*s*d*s*s-lga*2": "2. {}".format(lga['2']),
    "1*s*d*s*s-lga*3": "3. {}".format(lga['3']),
    "1*s*d*s*s-lga*4": "4. {}".format(lga['4']),
    "1*s*d*s*s-lga*5": "5. {}".format(lga['5']),
    "1*s*d*s*s-lga*6": "6. {}".format(lga['6']),
    "1*s*d*s*s-lga*7": "7. {}".format(lga['7']),
    "1*s*d*s*s-lga*8": "8. {}".format(lga['8']),
    "1*s*d*s*s-lga*9": "9. Lagelu, Egbeda, Ona Ara",
    "1*s*d*s*s-lga*10": "10. Iwajowa, Kajola",
    "1*s*d*s*s-lga*11": "11. Atisbo, Itesiwaju",
    "1*s*d*s*s-lga*12": "12. Saki East, Saki West",
    "1*s*d*s*s-lga*13":
    "13. Ibarapa North, Ibarapa East, Ibarapa Central, Ido",
    "1*s*d*s*s-lga*14": "14. Atiba, Ori Ire",
    "1*s*d*s*s-lga*15": "15. Oyo West, Oyo East, Afijio",
    "1*s*d*s*s-lga*16":
    "15. Ogbomosho North, Ogbomosho South, Surulere, Ogo Oluwa",
    "1*s*d*s*s-lga*17": "15. Irepo, Orelope, Olorunsogo",
    "1*s*d*s*s*d": "CON Select Town / Community",
    "1*s*d*s*s*d-com*1": "1. {}".format(town['1']),
    "1*s*d*s*s*d-com*2": "2. {}".format(town['2']),
    "1*s*d*s*s*d-com*3": "3. {}".format(town['3']),
    "1*s*d*s*s*d-com*4": "4. {}".format(town['4']),
    "1*s*d*s*s*d-com*5": "5. {}".format(town['5']),
    "1*s*d*s*s*d-com*6": "6. town 6, town 7, town 8",
    "1*s*d*s*s*d-com*7": "7. town 9, town 10",
    "1*s*d*s*s*d-com*8": "8. town 11, town 12",
    "1*s*d*s*s*d-com*9": "9. town 13, town 14",
    "1*s*d*s*s*d-com*10": "10. town 15, town 16, town 17, town 18",
    "1*s*d*s*s*d-com*11": "11. town 19, town 20",
    "1*s*d*s*s*d*d": "CON Select Preferred Hospital",
    "1*s*d*s*s*d*d-hos*1": "1. {}".format(hospitals['1']),
    "1*s*d*s*s*d*d-hos*2": "2. {}".format(hospitals['2']),
    "1*s*d*s*s*d*d-hos*3": "3. {}".format(hospitals['3']),
    "1*s*d*s*s*d*d-hos*4": "4. {}".format(hospitals['4']),
    "1*s*d*s*s*d*d-hos*5": "5.{}".format(hospitals['5']),
    "1*s*d*s*s*d*d*d": "CON Select Preferred Pharmacy",
    "1*s*d*s*s*d*d*d-pha*1": "1. {}".format(pharmacies['1']),
    "1*s*d*s*s*d*d*d-pha*2": "2. {}".format(pharmacies['2']),
    "1*s*d*s*s*d*d*d-pha*3": "3. {}".format(pharmacies['3']),
    "1*s*d*s*s*d*d*d-pha*4": "4. {}".format(pharmacies['4']),
    "1*s*d*s*s*d*d*d-pha*5": "5.{}".format(pharmacies['5']),
    "1*s*d*s*s*d*d*d*d": "CON Select Preferred Laboratory",
    "1*s*d*s*s*d*d*d*d-lab*1": "1. {}".format(laboratories['1']),
    "1*s*d*s*s*d*d*d*d-lab*2": "2. {}".format(laboratories['2']),
    "1*s*d*s*s*d*d*d*d-lab*3": "3. {}".format(laboratories['3']),
    "1*s*d*s*s*d*d*d*d-lab*4": "4. {}".format(laboratories['4']),
    "1*s*d*s*s*d*d*d*d-lab*5": "5.{}".format(laboratories['5']),
    "2": "END Registration Successful",
    "2*1": "Thank You!",
    "error": "END Error Ocurred",
}
